import = ["~/.config/alacritty/themes/dracula.toml"]

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
opacity = 0.9
decorations = "none"

[window.padding]
x = 7
y = 0

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"
