general.import = ["~/.config/alacritty/themes/dracula.toml"]

[font]
size = 15

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.9
decorations = "none"

[window.padding]
x = 7
y = 0

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"
