import = ["~/.config/alacritty/themes/dracula.toml"]

[font]
size = 15

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[window]
opacity = 0.9
decorations = "none"

[window.padding]
x = 7
y = 0


