# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    starship.toml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pibouill <pibouill@student.42prague.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/16 14:08:33 by pibouill          #+#    #+#              #
#    Updated: 2024/12/16 14:08:37 by pibouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

add_newline = false

#
## catppuccin_macchiato preset
#

palette = "catppuccin_macchiato"
# palette = "my_gruv"

[cmd_duration]
disabled = false

[character]
error_symbol = "[❯](red)"
vimcmd_symbol = "VI[❮](green)"

[directory]
truncation_length = 10
style = "bold lavender"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
disabled = false

[git_metrics]
disabled = false

[golang]
format = "[$symbol]($style)"
symbol = " "

[c]
symbol = " "
format = "[$symbol]($style)"

[python]
symbol = " "
format = "[${symbol}${virtualenv}]($style)"

[lua]
symbol = '🌙 '
format = "[$symbol]($style)"

[sudo]
disabled = false

[palettes.my_gruv]
bg_dim = "#232323"
bg0 = "#303030"
bg1 = "#3a3a3a"
bg2 = "#3c3c3c"
bg3 = "#504d47"
bg4 = "#5c5750"
bg5 = "#6a635c"

bg_statusline1 = "#3a3a3a"
bg_statusline2 = "#47423f"
bg_statusline3 = "#5c5750"

bg_diff_green = "#3e421f"
bg_visual_green = "#475141"
bg_diff_red = "#4a2625"
bg_visual_red = "#573c3c"
bg_diff_blue = "#11484a"
bg_visual_blue = "#455353"
bg_visual_yellow = "#5d4c38"
bg_current_word = "#4a413b"

fg0 = "#e6cb9c"
fg1 = "#f0d7af"

red = "#f76e68"
orange = "#f99559"
yellow = "#e8b256"
green = "#b3e074"
aqua = "#99e3ca"
blue = "#88c2e3"
purple = "#e09bc3"

bg_red = "#f76e68"
bg_green = "#b3e074"
bg_yellow = "#e8b256"

grey0 = "#8b7f70"
grey1 = "#a59484"
grey2 = "#b9aa98"


[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#d3869b"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
