return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
		"c",
        "vimdoc",
		"vim",
        "html",
        "json",
        "lua",
        "markdown",
       "markdown_inline",
        "python",
        "query",
        "regex",
        "vim",
        "yaml",
        "go",
        "bicep",
        "terraform",
        "c_sharp",
		"rust",
		"toml",
		"yaml",
		"cpp",
		"printf",
		"make",
		"cmake",
		"javascript",
		"diff",
		"help",
		"tmux",
      },
      highlight = { enable = true, additional_vim_regex_highlighting = false, },
    },
  },
}
